#!/bin/bash
set -x
function die {
echo An error has occured! Please fix this and start over!
exit 99
}
. conf
# Create scratch directory if it doesn't exist
mkdir -p scratch
cd scratch
# clean up and start over - remove everything including .git directories
rm -rf buildroot
git clone ${BUILDROOT} || die
cd buildroot
git checkout -b PBABUILD ${BUILDROOT_TAG}  || die
git reset --hard
git clean -df
# add out of tree build directoried and files
# 64 bit system
mkdir 64bit
cp ../../buildroot/64bit/.config 64bit/
cp ../../buildroot/64bit/* 64bit/
cp -r ../../buildroot/64bit/overlay 64bit/
# 32 bit system
mkdir 32bit
cp ../../buildroot/32bit/.config 32bit/
cp ../../buildroot/32bit/* 32bit/
cp -r ../../buildroot/32bit/overlay 32bit/
# add the current buildroot packages
sed -i '/sedutil/d' package/Config.in
sed -i '/menu "System tools"/a \\tsource "package/sedutil/Config.in"' package/Config.in
cp -r ../../buildroot/packages/sedutil/ package/
# Make a distribution from the current source
cd ../../..
autoreconf 
./configure
make dist
mkdir images/scratch/buildroot/dl/
cp sedutil-*.tar.gz images/scratch/buildroot/dl/
make distclean

# Expand the distribution tarball so we can use it as the Buildroot override.
# Override location is specified in the 'local.mk' file in buildroot/{32,64}bit
# directories.
# See also section 8.12.6 "Using Buildroot during development" in the
# Buildroot user manual.
cd images/scratch/buildroot/dl
tar xvfz sedutil-*.tar.gz
cd ..

# build the rootfs for 64 and 32 bit systems
echo Making the 64bit PBA Linux system
# Use olddefconfig to automatically set defaults for new config options
make O=64bit olddefconfig
# Remove legacy configuration marker that olddefconfig may have added
sed -i '/BR2_LEGACY/d' 64bit/.config
# Force truly sequential builds by setting MAKEFLAGS to prevent nested parallel jobs
# This is needed because glibc has race conditions even with -j1 at the top level
export MAKEFLAGS="-j1"
make -j1 O=64bit 2>&1 | tee 64bit/build_output.txt
echo Making the 32bit PBA Linux system
# Use olddefconfig to automatically set defaults for new config options
make O=32bit olddefconfig
# Remove legacy configuration marker that olddefconfig may have added
sed -i '/BR2_LEGACY/d' 32bit/.config
# Force truly sequential builds by setting MAKEFLAGS to prevent nested parallel jobs
export MAKEFLAGS="-j1"
make -j1 O=32bit 2>&1 | tee 32bit/build_output.txt
# back to where we started
cd ../..
exit 0
