#!/bin/bash
set -x
## Get version information
. conf
## Make a clean start
rm -rf scratch || true
mkdir -p scratch
cd scratch
wget https://www.kernel.org/pub/linux/utils/boot/syslinux/${SYSLINUX}.tar.xz
tar xf ${SYSLINUX}.tar.xz 
